build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: dind
  variables:
    DOCKER_DRIVER: "overlay2"
    IMAGE_NAME: "rdrit/glpi-agent"
  before_script:
    - docker login -u $CI_HUB_DOCKER_LOGIN -p $CI_HUB_DOCKER_PASSWORD
  script:
    # Logique pour déterminer le tag
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        export TAG_VERSION=$CI_COMMIT_TAG
      elif [ "$CI_COMMIT_BRANCH" == "main" ]; then
        export TAG_VERSION="latest"
      else
        export TAG_VERSION=$CI_COMMIT_REF_SLUG
      fi
    - docker build -t $IMAGE_NAME:$TAG_VERSION -f Dockerfile --no-cache .
    - docker push $IMAGE_NAME:$TAG_VERSION
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "main"'